openapi: 3.0.0

info:
  title: User Risks Story via API  
  description: Skills for getting User Risk Story via Graph API Call
  version: v1.0

servers:
  - url: https://graph.microsoft.com/v1.0/

paths:
  /identityProtection/riskyUsers/{riskyUserId}/history:
    get:
      operationId: GetUserRiskStory
      summary: Get risky user history
      parameters:
        - name: riskyUserId
          in: path
          schema:
            type: string
          required: true
          description: The unique identifier of the risky user
      responses:
        "200":
          description: OK
