openapi: 3.0.0
info:
  title: User Risks Story via API  
  description: Skills for getting User Risk Story via Graph API Call
  version: v1.0
paths:
  /identityProtection/riskyUsers/{riskyUserId}/history:
    get:
      summary: Get risky user history
      parameters:
        - name: riskyUserId
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier of the risky user
      responses:
              '200':
                description: Successful response
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/RiskyUserHistory'
              '4XX':
                description: Client error
              '5XX':
                description: Server error
      components:
        schemas:
          RiskyUserHistory:
            type: object
            properties:
              @odata.context:
                type: string
                description: OData context URL
              @microsoft.graph.tips:
                type: string
                description: Tips for using the API
              value:
                type: array
                items:
                  $ref: '#/components/schemas/RiskyUserHistoryItem'
          RiskyUserHistoryItem:
            type: object
            properties:
              id:
                type: string
                description: The unique identifier of the history item
              isDeleted:
                type: boolean
                description: Indicates if the item is deleted
              isProcessing:
                type: boolean
                description: Indicates if the item is being processed
              riskLevel:
                type: string
                description: The risk level of the user
              riskState:
                type: string
                description: The risk state of the user
              riskDetail:
                type: string
                description: The risk detail of the user
              riskLastUpdatedDateTime:
                type: string
                format: date-time
                description: The last updated date and time of the risk
              userDisplayName:
                type: string
                description: The display name of the user
              userPrincipalName:
                type: string
                description: The principal name of the user
              userId:
                type: string
                description: The unique identifier of the user
              initiatedBy:
                type: string
                description: The initiator of the action
              activity:
                type: object
                properties:
                  riskEventTypes:
                    type: array
                    items:
                      type: string
                  detail:
                    type: string
                    description: The detail of the activity
